INSERT INTO TB_STUDENT (COURSE, NAME, PERIOD, REGISTRATION) VALUES ('LICENCIATURA PLENA EM FÍSICA', 'FELIPE AMORIM', 5, 94586);
INSERT INTO TB_STUDENT (COURSE, NAME, PERIOD, REGISTRATION) VALUES ('LICENCIATURA EM MATEMÁTICA', 'JOSÉ DE ALMEIDA DA SILVA', 3, 95712);
INSERT INTO TB_STUDENT (COURSE, NAME, PERIOD, REGISTRATION) VALUES ('LICENCIATURA EM MATEMÁTICA', 'FERNANDO LISBOA DE CASTRO', 7, 75421);
INSERT INTO TB_STUDENT (COURSE, NAME, PERIOD, REGISTRATION) VALUES ('MEDICINA', 'KENDRA GOLÇALVES', 2, 75410);
INSERT INTO TB_STUDENT (COURSE, NAME, PERIOD, REGISTRATION) VALUES ('ENGENHARIA MECÂNICA', 'ENANDRO FIGUEROA', 6, 74256);
INSERT INTO TB_STUDENT (COURSE, NAME, PERIOD, REGISTRATION) VALUES ('BACHARELADO EM CIÊNCIAS BIOLOGICAS', 'AVELINO KENNIDE', 4, 14221);